spring:
  application:
    name: greeting-service

management:
  endpoints:
    web:
      exposure:
        include:
        - '*' 
  
greeting-service:
   greeting: "Olá ambiente DEV"
   default-value: "Mundo"
